server:
  port: 8282
  spring:
    datasource:
      url: jdbc:mysql://mysql-server:3306/authDB?createDatabaseIfNotExist=true
      username: root
      password: 1qaz2wsx@
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialization-mode: always
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace




