server:
  port: 8282

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emsauthDB?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      #      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl